# 抛出自定义错误
## 1. 错误的本质
```
当某些非期望的事情发生时程序就引发一个错误。
```
## 2. 在JavaScript中抛出错误
```
使用throw操作符抛出错误对象。如果没有try-catch语句捕获，会在控制台显示该错误消息。
    > throw new Error("somethingd bad happened.")
```
## 3. 抛出错误的好处
```
抛出自己的错误可以使用确切的文本共浏览器显示，便于调试和发现错误。
    > function getDivs(element) {
        if (element && element.getElementsByTagName) {
            return element.getElementByTagName("div);
        } else {
            throw new Error ("getDivs(): Argument must be a DOM element.");
        }
    }
```
## 4. 何时抛出错误
```
不能过度的使用抛出错误，以便造成性能问题。

抛出错误的经验法则：
    > 一旦修复了一个很难调试的错误，尝试增加一两个自定义错误。当再次发生错误时，将有助于解决问题。
    > 如果正在编写代码，思考一下：“我希望[某些事情]不会发生，如果发生，我的代码会一团糟糕”。这时，如果“某些事情”发生，抛出一个错误
    > 如果正在编写的代码别人也会使用，思考一下他们使用的方式，特定情况下抛出错误。
```
## 5. try-catch语句
```
JavaScript提供了try-catch语句，它能在浏览器处理抛出错误之前来解析它。可能引发错误的代码放在try块中，处理错误的代码放在catch块中。
可以增加finally块，不管代码有无错误发生，都会执行，try块中包含return语句必须等到finally块中代码执行后才能返回，因此一般不太常用。
    > try {
        something();
    } catch (ex) {
        //...
    } finally {
        //...
    }
```
## 6. 错误类型
```
7种错误类型：
    > Error: 所有错误基本类型，一般不会抛出
    > EvalError: 通过eval()函数执行代码发生的错误
    > RangeError: 数字超出边界时抛出
    > ReferenceError: 期望的对象不存在时抛出
    > SyntaxError：给eval()函数传递的代码有语法错误跑出
    > TypeError: 变量不是期望的类型时抛出
    > URIError: 给encodeURI()、encodeURIComponent()、decodeURI()或decodeURIComponent()等函数传递格式非法的URI字符串时抛出。
```
